// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/tools/cal.go

// Package mtools is a generated GoMock package.
package mtools

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCal is a mock of Cal interface
type MockCal struct {
	ctrl     *gomock.Controller
	recorder *MockCalMockRecorder
}

// MockCalMockRecorder is the mock recorder for MockCal
type MockCalMockRecorder struct {
	mock *MockCal
}

// NewMockCal creates a new mock instance
func NewMockCal(ctrl *gomock.Controller) *MockCal {
	mock := &MockCal{ctrl: ctrl}
	mock.recorder = &MockCalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCal) EXPECT() *MockCalMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockCal) Add(arg0, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", arg0, arg1)
}

// Add indicates an expected call of Add
func (mr *MockCalMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCal)(nil).Add), arg0, arg1)
}
